### ISSUE TITLE
TypeError: ResumeParser.parseResumeFile is not a function

### ISSUE THREAD

**Issue by louiscoetzee** [Ali925/resume-parser#8]
Hi, thanks for sharing this code, please help me, I am getting the following error: 

TypeError: ResumeParser.parseResumeFile is not a function

$ node index.js
C:\Projects\parser\index.js:5
  .parseResumeFile('./files/test1.pdf', './files/compiled') // input file, outpu
t dir
   ^

TypeError: ResumeParser.parseResumeFile is not a function
    at Object.<anonymous> (C:\Projects\parser\index.js:5:4)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:71:12)
    at internal/main/run_main_module.js:17:47

------- My index.js file ----------

const ResumeParser = require('resume-parser');

// From file to file
ResumeParser
  .parseResumeFile('./files/test1.pdf', './files/compiled') // input file, output dir
  .then(file => {
    console.log("Yay! " + file);
  })
  .catch(error => {
    console.error(error);
  });

**Comment by ritesh-hubbler** [comment]
It seems like the repository has resolved this issue, but hasn't updated in the node package. So you need to clone this repo of 'resume-parser' and then use it, it will work.
